export const BESTOF_CATEGORIES = [
  { id: "yemek", label: "Yemek" },
  { id: "meyve", label: "Meyve" },
  { id: "atistirmalik", label: "Atıştırmalık" },
] as const;

export type BestOfCategoryId = (typeof BESTOF_CATEGORIES)[number]["id"];

const RAW: Record<BestOfCategoryId, string[]> = {
  yemek: [
    "Adana kebap",
    "Urfa kebap",
    "İskender",
    "Döner dürüm",
    "Pilav üstü döner",
    "Lahmacun",
    "Kıymalı pide",
    "Kuşbaşılı pide",
    "Karışık pide",
    "Etli ekmek",
    "Çiğ köfte",
    "İçli köfte",
    "Kuru fasulye",
    "Pilav üstü kuru",
    "İmam bayıldı",
    "Karnıyarık",
    "Hünkar beğendi",
    "Tas kebabı",
    "Türlü",
    "Mantı",
    "Su böreği",
    "Sigara böreği",
    "Paçanga böreği",
    "Gözleme",
    "Menemen",
    "Sucuklu yumurta",
    "Kuymak",
    "Mıhlama",
    "Mercimek çorbası",
    "Ezogelin",
    "İşkembe çorbası",
    "Yayla çorbası",
    "Tarhana",
    "Tavuk suyu çorba",
    "Balık ekmek",
    "Hamsi tava",
    "Levrek ızgara",
    "Çipura ızgara",
    "Midye dolma",
    "Midye tava",
    "Kalamar tava",
    "Kokoreç",
    "Islak hamburger",
    "Tantuni",
    "Tavuk döner",
    "Tavuk şiş",
    "Çöp şiş",
    "Beyti",
    "Ali nazik",
    "Patlıcan kebap",
    "Testi kebabı",
    "Cağ kebabı",
    "Büryan",
    "Kuzu tandır",
    "Kaburga dolması",
    "Yaprak sarma",
    "Lahana sarması",
    "Biber dolması",
    "Zeytinyağlı enginar",
    "Barbunya pilaki",
    "Piyaz",
    "Çoban salata",
    "Gavurdağı",
    "Haydari",
    "Acılı ezme",
    "Humus",
    "Şakşuka",
    "Fava",
    "Kısır",
    "Mercimek köftesi",
    "Mücver",
    "Kabak çiçeği dolması",
    "Simit",
    "Poğaça",
    "Açma",
    "Boyoz",
    "Kumru",
    "Çiğ börek",
    "Sucuk ekmek",
    "Köfte ekmek",
    "Tekirdağ köfte",
    "İnegöl köfte",
    "Akçaabat köfte",
    "Pideli köfte",
    "Çökertme kebabı",
    "Orman kebabı",
    "Tavuk sote",
    "Et sote",
    "Sac kavurma",
    "Ciğer tava",
    "Arnavut ciğeri",
    "Tavuk kanat",
    "Nohut yemeği",
    "Etli taze fasulye",
    "Musakka",
    "Elbasan tava",
    "Fırın makarna",
    "Erişte",
    "Keşkek",
    "Hamsi buğulama",
    "Palamut ızgara",
    "Karides güveç",
    "Bamya",
    "Patates yemeği",
    "Kelle paça",
    "Mumbar",
    "Lahmacun Antep usulü",
    "Kaygana",
    "Pastırmalı yumurta",
    "Deniz börülcesi",
    "Zeytinyağlı fasulye",
    "Tavuklu pilav",
    "Bulgur pilavı",
    "İç pilav",
    "Kuru patlıcan dolması",
    "Etli yaprak sarma",
    "Çerkez tavuğu",
    "Papaz yahnisi",
    "Kuru köfte",
    "İzmir köfte",
    "Kadınbudu köfte",
    "Dalyan köfte",
    "Tas kebap pilav",
    "Kuzu haşlama",
    "Etli bamya",
    "Karnabahar graten",
    "Ispanak yemeği",
    "Kabak yemeği",
  ],
  meyve: [
    "Elma",
    "Amasya elması",
    "Armut",
    "Deveci armudu",
    "Muz",
    "Portakal",
    "Finike portakalı",
    "Mandalina",
    "Greyfurt",
    "Limon",
    "Çilek",
    "Kiraz",
    "Napolyon kirazı",
    "Vişne",
    "Kayısı",
    "Malatya kayısısı",
    "Şeftali",
    "Nektarin",
    "Erik",
    "Can eriği",
    "Mürdüm eriği",
    "Üzüm",
    "Sultani üzüm",
    "Siyah üzüm",
    "Razakı üzüm",
    "Karpuz",
    "Diyarbakır karpuzu",
    "Kavun",
    "Kırkağaç kavunu",
    "İncir",
    "Aydın inciri",
    "Bursa siyahı incir",
    "Nar",
    "Ayva",
    "Trabzon hurması",
    "Kivi",
    "Ananas",
    "Mango",
    "Avokado",
    "Ahududu",
    "Böğürtlen",
    "Dut",
    "Karadut",
    "Yenidünya",
    "Muşmula",
    "İğde",
    "Kızılcık",
    "Hünnap",
    "Keçiboynuzu",
    "Kestane",
    "Ahlat",
    "Yaban mersini",
    "Lime",
    "Kumkuat",
    "Pomelo",
    "Hindistan cevizi",
    "Papaya",
    "Ejder meyvesi",
    "Liçi",
    "Passion fruit",
    "Greyfurt yeşil",
    "Şeker pare kavunu",
    "Honeydew kavun",
    "Çilek (toros)",
  ],
  atistirmalik: [
    "Simit",
    "Açma",
    "Poğaça",
    "Boyoz",
    "Gevrek",
    "Sucuklu tost",
    "Kaşarlı tost",
    "Kumpir",
    "Islak hamburger",
    "Midye dolma",
    "Çiğ köfte dürüm",
    "İçli köfte",
    "Mercimek köfte",
    "Sigara böreği",
    "Paçanga",
    "Patates kızartması",
    "Soğan halkası",
    "Leblebi",
    "Ayçekirdeği",
    "Kabak çekirdeği",
    "Fındık",
    "Antep fıstığı",
    "Badem",
    "Ceviz",
    "Kaju",
    "Pestil",
    "Köme",
    "Lokum",
    "Pişmaniye",
    "Cezerye",
    "Tahin helva",
    "Yaz helvası",
    "Kakaolu gofret",
    "Dido",
    "Albeni",
    "Metro",
    "Hobby",
    "Halley",
    "Biskrem",
    "Tutku",
    "Çizi",
    "Hanımeller",
    "Petibör",
    "Cips",
    "Nachos",
    "Patlamış mısır",
    "Çubuk kraker",
    "Kakaolu süpürge",
    "Ülker çikolata",
    "Eti Canga",
    "Cocostar",
    "Çikolatalı gofret",
    "Kayseri sucuğu",
    "Pastırma",
    "Kaşar küp",
    "Hellim",
    "Peynirli poğaça",
    "Zeytinli poğaça",
    "Sade açma",
    "Simit sandwich",
    "Lahmacun dürüm",
    "Tost ekmek arası",
    "Mısır haşlama",
    "Kestane kebap",
  ],
};

export type BestOfItem = {
  id: string;
  cat: BestOfCategoryId;
  name: string;
};

export const BESTOF_ITEMS: BestOfItem[] = (
  Object.entries(RAW) as [BestOfCategoryId, string[]][]
).flatMap(([cat, rows]) =>
  rows.map((name, index) => ({
    id: `${cat}-${index + 1}`,
    cat,
    name,
  })),
);
