export const RATHER_CATEGORIES = [
  { id: "tanisma", label: "Tanışma" },
  { id: "yemek", label: "Yemek" },
  { id: "karakter", label: "Karakter" },
  { id: "gunluk", label: "Günlük" },
  { id: "hayal", label: "Hayal" },
  { id: "komik", label: "Komik" },
  { id: "tatil", label: "Tatil" },
  { id: "kultur", label: "Kültür" },
  { id: "dostluk", label: "Dostluk" },
  { id: "para", label: "Para" },
  { id: "cocukluk", label: "Çocukluk" },
  { id: "masa", label: "Masa başı" },
] as const;

export type RatherCategoryId = (typeof RATHER_CATEGORIES)[number]["id"];

const RAW: Record<RatherCategoryId, [string, string][]> = {
  tanisma: [
    ["İnsanları hemen açarsın", "Önce izler, sonra konuşursun"],
    ["İlk mesajı sen atarsın", "Karşı tarafın yazmasını beklersin"],
    ["Lakabınla anılmak", "Adının tam haliyle anılmak"],
    ["Kalabalık masada parlamak", "İki kişiyle derin konuşmak"],
    ["Geçmişini hemen anlatmak", "Yavaş yavaş açılmak"],
    ["Göz teması kurmak", "Gülümseyerek bakmak"],
    ["Aynı şehri gezerek tanışmak", "Uzun bir yemekte tanışmak"],
    ["İlk izlenime güvenmek", "İkinci buluşmayı beklemek"],
    ["Ortak playlist’ten başlamak", "Ortak yemekten başlamak"],
    ["Soru sorarak tanımak", "Hikaye dinleyerek tanımak"],
    ["Erken samimi olmak", "Mesafeyi koruyup ısınmak"],
    ["İsmini unutmamak", "Yüzünü unutmamak"],
    ["Aynı masada sessizce oturmak", "Hemen sohbeti açmak"],
    ["Komik bir sır paylaşmak", "Ciddi bir hayal paylaşmak"],
    ["İnsanı işinden tanımak", "İnsanı boş zamanından tanımak"],
    ["Hızlı karar vermek", "Bir gece düşünmek"],
    ["Aynı şakayı yapmak", "Aynı şarkıyı söylemek"],
    ["Tokalaşarak tanışmak", "Sarılıp tanışmak"],
    ["Telefonunu hemen vermek", "Önce sohbeti uzatmak"],
    ["Grupta tanışmak", "Baş başa tanışmak"],
    ["İlk cümlede espri", "İlk cümlede dürüstlük"],
    ["Aynı takımı tutmak", "Aynı yemeği sevmek"],
    ["Sessiz gücünü göstermek", "Gürültülü neşeni göstermek"],
    ["Kısa ve net anlatmak", "Uzun ve renkli anlatmak"],
    ["İnsanı ailesinden tanımak", "İnsanı arkadaşlarından tanımak"],
    ["Aynı kahveyi içmek", "Aynı filmi izlemek"],
    ["Hatalarını başta söylemek", "Güzelliklerini başta söylemek"],
    ["Yeni birine ‘sen’ demek", "Bir süre ‘siz’ demek"],
    ["Masada yerini değiştirmek", "Aynı yerde kalıp ısınmak"],
    ["İlk gece çok konuşmak", "İlk gece çok dinlemek"],
  ],
  yemek: [
    ["Kahve", "Çay"],
    ["Tatlı", "Tuzlu"],
    ["Pizza", "Burger"],
    ["Makarna", "Pilav"],
    ["Çorba ile başlamak", "Salata ile başlamak"],
    ["Acı seven", "Acısız seven"],
    ["Deniz ürünü", "Kırmızı et"],
    ["Sokak lezzeti", "Şef tabağı"],
    ["Kahvaltıyı kaçırmamak", "Gece atıştırmasını kaçırmamak"],
    ["Dondurma", "Sütlaç"],
    ["Lahmacun", "Pide"],
    ["Mantı", "Börek"],
    ["Ayran", "Şalgam"],
    ["Baklava", "Künefe"],
    ["Menemen", "Omlet"],
    ["Izgara", "Fırın"],
    ["Paylaşarak yemek", "Kendi tabağına odaklanmak"],
    ["Hesabı ayırmak", "Sıra ile ısmarlamak"],
    ["Yemeği fotoğraflamak", "Hemen dalmak"],
    ["Baharatı abartmak", "Sade bırakmak"],
    ["Sıcak çorba", "Soğuk meze"],
    ["Ev yemeği", "Dışarıda keşif"],
    ["Tatlıyı başta yemek", "Tatlıyı sonda yemek"],
    ["Bol sos", "Az sos"],
    ["Ekmekle silmek", "Ekmeğe dokunmamak"],
    ["Aynı siparişi vermek", "Herkes farklı denesin"],
    ["Çayın açık olması", "Çayın demli olması"],
    ["Mevsim meyvesi", "Çikolata"],
    ["Balık ekmek", "Kokoreç"],
    ["Sunday brunch", "Gece 01.00 tostu"],
  ],
  karakter: [
    ["Planlı yaşamak", "Ani karar vermek"],
    ["Erken kalkan", "Gece kuşu"],
    ["Kontrol sende olsun", "Akışa bırak"],
    ["Az konuşup öz konuşmak", "Bol bol anlatmak"],
    ["Rekabeti sevmek", "Birlikte kazanmayı sevmek"],
    ["Risk almak", "Güvende kalmak"],
    ["Özür dilemek", "Telafi etmek"],
    ["Lider olmak", "Sessizce yönlendirmek"],
    ["Duyguyu hemen göstermek", "İçinde evrilmesini beklemek"],
    ["Mükemmeliyetçi", "İdare ederci"],
    ["Kalabalıktan enerji almak", "Yalnızlıktan enerji almak"],
    ["Eskiye bağlı", "Yeniyi meraklı"],
    ["İnatçı", "Uyumlu"],
    ["Şüpheci", "Safça güvenen"],
    ["Düzenli çanta", "Çantada kayıp medeniyet"],
    ["Saatine sadık", "‘5 dakika’ diyen"],
    ["Eleştiriyi duymak", "Övgüyü duymak"],
    ["Kural koymak", "İstisna yapmak"],
    ["Hemen karar", "İki kere düşün"],
    ["Sözünde durmak", "Esnek olmak"],
    ["Gülerek geçiştirmek", "Ciddileşip çözmek"],
    ["Önde yürümek", "Yanda yürümek"],
    ["Detay avcısı", "Büyük resmi gören"],
    ["Sessiz güç", "Görünür neşe"],
    ["Unutkan bağışlayıcı", "Unutmayan ama barışan"],
    ["Kendi yolun", "Beraber yol"],
    ["Az eşya", "Anı dolu ev"],
    ["Hemen yardım", "Önce sormak"],
    ["Sözlü anlatmak", "Yazarak anlatmak"],
    ["İç sesini dinlemek", "Yakınını dinlemek"],
  ],
  gunluk: [
    ["Sabah sporu", "Akşam yürüyüşü"],
    ["Dușta şarkı", "Mutfakta şarkı"],
    ["Alarmı ertelemek", "İlk alarmda kalkmak"],
    ["Toplu taşıma", "Yürümek"],
    ["Bildirimleri açık", "Rahatsız etme açık"],
    ["Not defteri", "Telefona yazmak"],
    ["Evi toplamadan çıkmamak", "Dağınık bırakıp kaçmak"],
    ["Öğle uykusu", "Gece fazladan bir saat"],
    ["Yağmurlu gün ev", "Yağmurlu gün dışarı"],
    ["Aynı kahve her gün", "Her gün başka bir şey"],
    ["Çamaşırı hemen asmak", "Makinede bekletmek"],
    ["Pazartesi nefret", "Pazartesi sıfırlama"],
    ["Kulaklıkla dünya", "Etrafı dinlemek"],
    ["Mesajı hemen yanıt", "Kuyrukta bekletmek"],
    ["Alışveriş listesi", "Rafta kaybolmak"],
    ["Erken yatmak", "Bir bölüm daha"],
    ["Sıcak duş", "Soğuk duş"],
    ["Pencereden hava", "Klima"],
    ["Ayakkabıyı kapıda", "İçeri kadar"],
    ["Güne sessiz başlamak", "Güne müzikle başlamak"],
    ["Yemek hazırlamak", "Hazır yemek"],
    ["Hafta içi disiplin", "Hafta sonu kaos"],
    ["Saati bozmadan yaşamak", "Rötarı kabullenmek"],
    ["Tek tabak yıkamak", "Hepsi biriksin"],
    ["Güneşe karşı oturmak", "Gölgede oturmak"],
    ["Aynı yoldan işe", "Her gün yeni sokak"],
    ["Çantada powerbank", "Şansına güvenmek"],
    ["Kıyafeti akşamdan seçmek", "Sabah karar vermek"],
    ["Sessiz ev", "Arka planda dizi"],
    ["Erken alışveriş", "Son dakika market"],
  ],
  hayal: [
    ["Denizde ev", "Dağda ev"],
    ["Zamanı durdurmak", "Geleceği görmek"],
    ["Uçabilmek", "Görünmez olmak"],
    ["Bir yıl dünyayı gezmek", "Bir yıl bir zanaat öğrenmek"],
    ["Ünlü olmak", "Sessizce özgür olmak"],
    ["Geçmişe bir mektup", "Geleceğe bir mektup"],
    ["Süper bellek", "Süper sakinlik"],
    ["Ada hayatı", "Büyük şehir ışığı"],
    ["Kitap yazmak", "Film çekmek"],
    ["Sonsuz bilet", "Sonsuz konaklama"],
    ["Bir dilek hakkı", "Üç küçük dilek"],
    ["Hayvanlarla konuşmak", "Herkesin dilini bilmek"],
    ["Gece hiç bitmesin", "Yaz hiç bitmesin"],
    ["Sahilde kahve dükkanı", "Şehirde küçük bir sahne"],
    ["Zaman yolculuğu", "Uzay yolculuğu"],
    ["Görülmez bir iyilik", "Büyük bir alkış"],
    ["Kendi adanı kurmak", "Kayıp bir şehri bulmak"],
    ["Müze müdürü", "Orkestra şefi"],
    ["Ömür boyu yaz", "Ömür boyu sonbahar"],
    ["Tekrar 18 olmak", "Bilge 80 olmak"],
    ["Sihirli kapı", "Sihirli anahtar"],
    ["Kütüphanede kaybolmak", "Mutfakta kaybolmak"],
    ["Dünyayı değiştiren fikir", "Birini değiştiren söz"],
    ["Görünür iz bırakmak", "İsimsiz kalmak"],
    ["Kendi takımını kurmak", "Kendi restoranını açmak"],
    ["Yıldızların altında uyumak", "Gökdelenin tepesinde uyanmak"],
    ["Hiç korkmamak", "Hiç pişman olmamak"],
    ["Bir gün kral", "Bir ömür gezgin"],
    ["Müzik aletin olsun", "Fırçanın olsun"],
    ["Kaybolmuş bir harita", "Bitmemiş bir mektup"],
  ],
  komik: [
    ["Yanlış isimle hitap etmek", "Yanlış masaya oturmak"],
    ["Çorabın tekini kaybetmek", "Şarj aletini evde unutmak"],
    ["Gülünce horlamak", "Yerken konuşmak"],
    ["Dans ederken abartmak", "Şarkıda sözü uydurmak"],
    ["Selfie’de göz kırpmak", "Grup fotoğrafında kaybolmak"],
    ["Yanlış sohbete gülmek", "Yanlış kişiye el sallamak"],
    ["Tuz yerine şeker", "Şeker yerine tuz"],
    ["Asansörde şarkı", "Merdivende nefessiz kalmak"],
    ["İnatla kaybolmak", "İnatla yol sormamak"],
    ["Kahveyi devirmek", "Hesabı ıslatmak"],
    ["Taklidini yapmak", "Eski bir dansı hatırlamak"],
    ["Yanlış odaya girmek", "Yanlış durağa inmek"],
    ["Gülmekten su burnundan", "Hıçkırığı tutamamak"],
    ["Kedi gibi sızmak", "Köpek gibi heyecanlanmak"],
    ["İki çorap farklı", "Tişört ters"],
    ["Espri patlamayınca sessizlik", "Espriyi kendin anlatıp gülmek"],
    ["Menüde 10 dakika kaybolmak", "Garsona 3 kere aynı şeyi sormak"],
    ["Fotoğrafta hep gözün kapalı", "Fotoğrafta hep ağzın açık"],
    ["Yanlış playlist", "Yanlış alarm saati"],
    ["Sakızla konuşmak", "Kürdanla konuşmak"],
    ["İnatçı fermuar", "Kaybolan anahtar"],
    ["Kendi ses kaydından korkmak", "Kendi dans videondan korkmak"],
    ["Yanlış ‘günaydın’ saati", "Yanlış ‘iyi geceler’ saati"],
    ["Masada herkesin yemeğini tatmak", "Kendi tabağını kimseye vermemek"],
    ["Gülünce elini vurmak", "Gülünce masayı sallamak"],
    ["İsmini heceletmek", "Adres tarifinde kaybolmak"],
    ["Çantan dibini görmek", "Cebinde sürpriz kâğıt"],
    ["Yanlış filmi izledim demek", "Yanlış şarkıyı söylemek"],
    ["Kaşığı düşürmek", "Peçeteyi uçurmak"],
    ["Komik bir yalan", "Daha komik bir gerçek"],
  ],
  tatil: [
    ["Deniz", "Dağ"],
    ["Otel konforu", "Çadır macerası"],
    ["Planlı itinerary", "Günübirlik sürpriz"],
    ["Erken uçuş", "Gece otobüsü"],
    ["Aynı yere dönmek", "Hiç gitmediğin yer"],
    ["Müze günü", "Plaj günü"],
    ["Şehir tatili", "Köy tatili"],
    ["Valizi tam doldurmak", "Sadece sırt çantası"],
    ["Yerel yemek", "Güvenli bildiğin lezzet"],
    ["Gün doğumu", "Gün batımı"],
    ["Tek başına yol", "Kalabalık kervan"],
    ["Ada", "Çöl"],
    ["Tren penceresi", "Araba yolculuğu"],
    ["Rezervasyonlu restoran", "Sokağın en kalabalık tezgahı"],
    ["Fotoğraf çekmek", "Sadece bakmak"],
    ["İlk gün dinlenmek", "İlk gün keşif"],
    ["Kar tatili", "Yaz adası"],
    ["All inclusive", "Sokak sokak yemek"],
    ["Haritayı kaybetmek", "Telefonu kaybetmek"],
    ["Eski bir pansiyon", "Yeni bir tasarım otel"],
    ["Göl", "Şelale"],
    ["Gece pazarı", "Sabah balık hali"],
    ["Bir ülke, on gün", "On ülke, on gün"],
    ["Yürüyerek kaybolmak", "Taksiyle yetişmek"],
    ["Hatıra dolu bavul", "Sadece anılar"],
    ["Kamp ateşi", "Otel jakuzisi"],
    ["Yol müziği yüksek", "Yol sessiz"],
    ["Aynı otel her yıl", "Her yıl başka kıta"],
    ["Erken check-in", "Geç check-out"],
    ["Tatilde iş maili yok", "Bir göz atıp kapatmak"],
  ],
  kultur: [
    ["Sinema", "Tiyatro"],
    ["Dizi binge", "Haftalık bölüm"],
    ["Roman", "Şiir"],
    ["Konser", "Sergi"],
    ["Yerli film", "Yabancı film"],
    ["Komedi", "Gerilim"],
    ["Altyazı", "Dublaj"],
    ["Canlı müzik", "Kulaklık ve yalnızlık"],
    ["Eski klasikler", "Bu yılın hitleri"],
    ["Podcast", "Radyo"],
    ["Müzede kaybolmak", "Sahilde kitap"],
    ["Stand-up", "Müzikal"],
    ["Belgesel", "Bilim kurgu"],
    ["Tekrar izlenen film", "Hiç bitmeyen dizi"],
    ["Kütüphane", "Plakçı"],
    ["Gece sineması", "Gündüz matinesi"],
    ["Şarkı sözü ezberlemek", "Melodiyi ıslıkla bilmek"],
    ["Yazar olmak", "Yönetmen olmak"],
    ["Perde arkası", "Sahne ışığı"],
    ["Çizgi roman", "Uzun roman"],
    ["Dans etmek", "Sadece dinlemek"],
    ["Karanlık salon", "Açık hava sinema"],
    ["Bir şarkıda ağlamak", "Bir sahnede gülmek"],
    ["Oyun konsolu", "Masa oyunu"],
    ["Bilet kuyruğu", "Evde yayın"],
    ["Koro", "Solo"],
    ["Siyah beyaz film", "Renk cümbüşü"],
    ["Şiir gecesi", "Açık mikrofon"],
    ["Kitabı e-kitap", "Kokulu kâğıt"],
    ["Jeneriği sonuna kadar", "Hemen kapatmak"],
  ],
  dostluk: [
    ["Eski dost", "Yeni ama samimi"],
    ["Her gün mesaj", "Ayda bir uzun sohbet"],
    ["Sır tutmak", "Dürüstçe uyarmak"],
    ["Birlikte susmak", "Birlikte gülmek"],
    ["Zor günde yanında olmak", "İyi günde kutlamak"],
    ["Aynı şakayı 10 yıl", "Her yıl yeni bir içe bakış"],
    ["Gece 03.00 araması", "Sabah kahvesi rutinı"],
    ["Ortak sır", "Ortak hedef"],
    ["Tartışıp barışmak", "Hiç küsmeden konuşmak"],
    ["Aynı masada 4 saat", "Kısa ama sık görüşmek"],
    ["Hediye almak", "Vakit ayırmak"],
    ["Seni tanıyan bir bakış", "Seni anlatan bir cümle"],
    ["Grup sohbeti", "İkili sohbet"],
    ["Yol arkadaşı", "Sır arkadaşı"],
    ["Aynı şehri paylaşmak", "Uzak ama bağlı kalmak"],
    ["Özür beklememek", "Özürü büyütmek"],
    ["Birlikte yemek yapmak", "Birlikte yemek ısmarlamak"],
    ["Doğum gününü hatırlamak", "Rastgele sürpriz"],
    ["Sert dürüstlük", "Yumuşak teselli"],
    ["Aynı takım forması", "Aynı çalma listesi"],
    ["Sessizce yardım", "Açıkça omuz vermek"],
    ["Eski fotoğraflara gülmek", "Yeni planlar yazmak"],
    ["Kavga etmeden ayrılmak", "Kavga edip daha bağlanmak"],
    ["Bir sırrı emanet", "Bir hayali emanet"],
    ["Seni utandıran anı", "Seni gururlandıran anı"],
    ["Aynı masada susmak rahat", "Aynı masada hiç susmamak"],
    ["Dostun yemeğini yemek", "Dostuna son lokmayı vermek"],
    ["Yol tarif etmek", "Yolda kaybolmak"],
    ["Aynı şakaya kızmak", "Aynı şakaya bayılmak"],
    ["El sıkışmak", "Omuz omuza yürümek"],
  ],
  para: [
    ["Biriktirmek", "Güzel bir şey için harcamak"],
    ["Nakit", "Kart"],
    ["Pahalı ve az", "Uygun ve bol"],
    ["Hesabı kapamak", "Hesabı bölmek"],
    ["İkinci el hazine", "Yeni ve garantili"],
    ["Maaş günü kutlamak", "Maaş günü planlamak"],
    ["Sürpriz hediye", "İstenen hediye"],
    ["Ucuza kaçmak", "Bir kez olsun şımarmak"],
    ["Yatırım konuşmak", "Tatil konuşmak"],
    ["Bahşişi yuvarlamak", "Tam hesap"],
    ["İndirim kovalamak", "Vaktini kovalamak"],
    ["Ev almak", "Dünyayı gezmek"],
    ["Sigorta", "Macera fonu"],
    ["Marka", "Kalite sessiz olsun"],
    ["Ortak kumbara", "Ayrı cüzdan"],
    ["Piyango bileti", "Düzenli birikim"],
    ["Lüks bir akşam", "On mütevazı akşam"],
    ["Borcu hemen kapatmak", "Taksiti sevmek"],
    ["Pahalı kahve", "Pahalı kitap"],
    ["İlk maaşın anısı", "İlk birikimin anısı"],
    ["Pazarlık", "Fiyatı kabul"],
    ["İkram etmek", "İkramı kabul etmek"],
    ["Az kazanıp rahat", "Çok kazanıp tempo"],
    ["Emeklilik hayali", "Bugünün keyfi"],
    ["Ortak hesap", "Net bölüşmek"],
    ["Kumbara kırmak", "Kumbara büyütmek"],
    ["İyi bir ayakkabı", "İyi bir yemek"],
    ["Döviz konuşmak", "Dondurma konuşmak"],
    ["Fatura alarmı", "Sürpriz ek ücret"],
    ["‘Ben öderim’", "‘Sırayla ödeyelim’"],
  ],
  cocukluk: [
    ["Dışarıda mahalle", "İçeride Lego"],
    ["Çizgi film", "Saklambaç"],
    ["Yaz tatili köy", "Yaz tatili deniz"],
    ["Okul servisi", "Yürüyerek okul"],
    ["Öğretmenin gözdesi", "Teneffüs kralı"],
    ["Günlük tutmak", "Duvara resim"],
    ["Bisiklet", "Patens"],
    ["Abur cubur yasak", "Abur cubur serbest"],
    ["Kardeşle oda", "Tek başına oda"],
    ["Yaz okulu", "Boş yaz"],
    ["Masal", "Çizgi roman"],
    ["Annemin yemeği", "Babanın kahvaltısı"],
    ["İlk evcil hayvan", "İlk en yakın arkadaş"],
    ["Kar tatili sevinci", "Yaz tatili bitmesin"],
    ["Ödevi akşam", "Ödevi sabah"],
    ["Saklı defter", "Açık günlük"],
    ["Mahalle maçı", "Bilgisayar oyunu"],
    ["Kırmızı karne korkusu", "Takdir gururu"],
    ["Büyümek istemek", "Çocuk kalmak"],
    ["Park salıncağı", "Deniz simidi"],
    ["İlk sahne korkusu", "İlk gol sevinci"],
    ["Yastık savaşı", "Su savaşı"],
    ["Gizli kulübe", "Çatı katı"],
    ["Öğle uykusu isyanı", "Gece erken yatmak isyanı"],
    ["Bayram harçlığı", "Bayram öpücüğü"],
    ["İlk konser hayali", "İlk maç hayali"],
    ["Sınıfta arka sıra", "Sınıfta ön sıra"],
    ["Öğretmen olmak", "Astronot olmak"],
    ["Kardan adam", "Kumdan kale"],
    ["Masal sonu mutlu bitsin", "Biraz korksun ki eğlensin"],
  ],
  masa: [
    ["Hesabı isteyen", "Bir şey daha söyleyen"],
    ["Menüyü ezberlemek", "Garsona bırakmak"],
    ["Pencere kenarı", "Ortadaki kalabalık masa"],
    ["Çayı taze taze", "Hesap gelene kadar sohbet"],
    ["Telefonu ters çevirmek", "Bir fotoğraf izni"],
    ["Ortak mezeler", "Herkes kendi tabağı"],
    ["Gürültülü masa", "Fısıltılı masa"],
    ["Erken kalkıp gitmek", "Kapanışa kadar kalmak"],
    ["Aynı mekânın müdavimi", "Her hafta yeni yer"],
    ["N devirmek", "Tuzu devirmek"],
    ["Garsonla muhabbet", "Sessiz sipariş"],
    ["Tatlıyı bölüşmek", "Ayrı ayrı tatlı"],
    ["Masada oyun", "Masada dedikodu"],
    ["Dışarıda oturmak", "İçeride köşe"],
    ["Hesabı şaşırınca gülmek", "Hesabı şaşırınca panik"],
    ["Su sade", "Su sodalı"],
    ["Ekmek sepeti bitsin", "Tatlı menüsü açılsın"],
    ["Kalabalık rezervasyon", "İki kişilik sürpriz"],
    ["İlk gelen siparişi verir", "Herkes gelsin diye bekler"],
    ["Masa örtüsü klasik", "Çıplak ahşap masa"],
    ["Çaydanlık masada", "Tek tek bardak"],
    ["Açık mutfağı izlemek", "Sokağı izlemek"],
    ["Hesap kâğıdını saklamak", "Hemen unutmak"],
    ["‘Bir şey daha’ turu", "‘Hesap lütfen’ turu"],
    ["Masa oyununu kaybetmek", "Hesabı kapamak"],
    ["İmzalı peçete şakası", "Bardak kadeh tokuşturmak"],
    ["Yemeği soğutmadan konuşmak", "Önce yemek sonra sohbet"],
    ["Aynı masada 3 saat", "İki mekân bir gece"],
    ["Bahşişi yuvarlak", "Bahşişi içinden geldiği gibi"],
    ["Masada sır paylaşmak", "Masada plan yapmak"],
  ],
};

export type RatherQuestion = {
  id: string;
  cat: RatherCategoryId;
  a: string;
  b: string;
};

export const RATHER_QUESTIONS: RatherQuestion[] = (
  Object.entries(RAW) as [RatherCategoryId, [string, string][]][]
).flatMap(([cat, rows]) =>
  rows.map(([a, b], index) => ({
    id: `${cat}-${index + 1}`,
    cat,
    a,
    b,
  })),
);
