export const RATHER_CATEGORIES = [
  { id: "tanisma", label: "Tanışma" },
  { id: "yemek", label: "Yemek" },
  { id: "karakter", label: "Karakter" },
  { id: "gunluk", label: "Günlük" },
  { id: "hayal", label: "Hayal" },
  { id: "komik", label: "Komik" },
  { id: "tatil", label: "Tatil" },
  { id: "kultur", label: "Kültür" },
  { id: "dostluk", label: "Dostluk" },
  { id: "para", label: "Para" },
  { id: "cocukluk", label: "Çocukluk" },
  { id: "masa", label: "Masa başı" },
] as const;

export type RatherCategoryId = (typeof RATHER_CATEGORIES)[number]["id"];

const RAW: Record<RatherCategoryId, [string, string][]> = {
  tanisma: [
    ["İnsanları hemen açarsın", "Önce izler, sonra konuşursun"],
    ["İlk mesajı sen atarsın", "Karşı tarafın yazmasını beklersin"],
    ["Lakabınla anılmak", "Adının tam haliyle anılmak"],
    ["Kalabalık masada parlamak", "İki kişiyle derin konuşmak"],
    ["Geçmişini ilk gecede anlatmak", "Haftalarca yavaş yavaş açılmak"],
    ["Göz göze gelince kaçmamak", "Gülümseyip bakışı indirmek"],
    ["Şehri geze geze tanışmak", "Uzun bir yemekte tanışmak"],
    ["İlk izlenime güvenmek", "İkinci buluşmayı beklemek"],
    ["Ortak çalma listesinden başlamak", "Ortak bir yemekten başlamak"],
    ["Soru yağmuruyla tanımak", "Hikâyesini dinleyerek tanımak"],
    ["İlk günden samimi olmak", "Mesafeyi koruyup ısınmak"],
    ["İsmini bir daha unutmamak", "Yüzünü yıllar sonra hatırlamak"],
    ["Aynı masada rahatça susmak", "Sessizliği hemen bozmak"],
    ["Komik bir sır paylaşmak", "Ciddi bir hayal paylaşmak"],
    ["İnsanı işinden tanımak", "İnsanı boş gününden tanımak"],
    ["Hemen karar vermek", "Bir gece yastığa danışmak"],
    ["Aynı şakayı yapmak", "Aynı şarkıyı mırıldanmak"],
    ["Tokalaşarak tanışmak", "Sarılıp tanışmak"],
    ["Numarasını hemen vermek", "Sohbeti uzatıp sonra istemek"],
    ["Kalabalıkta tanışmak", "Baş başa tanışmak"],
    ["İlk cümlede espri", "İlk cümlede dürüstlük"],
    ["Aynı takımı tutmak", "Aynı yemeği sevmek"],
    ["Sessiz gücünü göstermek", "Gürültülü neşeni göstermek"],
    ["Kısa ve net anlatmak", "Uzun ve renkli anlatmak"],
    ["İnsanı ailesinden tanımak", "İnsanı arkadaşlarından tanımak"],
    ["Aynı kahveyi içmek", "Aynı filmi izlemek"],
    ["Hatalarını başta söylemek", "Güzelliklerini başta söylemek"],
    ["Yeni birine hemen ‘sen’ demek", "Bir süre ‘siz’ deyip ısınmak"],
    ["Masada yerini değiştirmek", "Aynı yerde kalıp ısınmak"],
    ["İlk gece çok konuşmak", "İlk gece çok dinlemek"],
    ["Tanışırken ‘ne iş yapıyorsun’", "Tanışırken ‘neyden mutlu olursun’"],
    ["Ortak tanıdıkla tanışmak", "Tamamen yabancı kalmak"],
    ["İlk buluşmada yürüyüş", "İlk buluşmada uzun kahve"],
    ["Instagram’dan bakıp gelmek", "Hiç bakmadan sürprizle gelmek"],
    ["Aynı mahalleden olmak", "Farklı şehirden olup denk gelmek"],
    ["Seni güldürenle tanışmak", "Seni düşündürenle tanışmak"],
    ["Hemen ‘bir daha görüşelim’ demek", "Kapıda ‘görüşürüz’ deyip beklemek"],
    ["Aynı masada doğum günü kutlamak", "Aynı masada sır paylaşmak"],
    ["İlk izlenimde kılık", "İlk izlenimde ses"],
    ["Sohbete havadan başlamak", "Sohbete doğrudan dalmak"],
    ["Aynı kitabı okumuş olmak", "Aynı diziyi bitirmiş olmak"],
    ["Tanışınca fotoğraf çekilmek", "Tanışınca sadece kalmak"],
    ["Seni merakta bırakan biri", "Seni hemen rahatlatan biri"],
    ["Aynı otobüste denk gelmek", "Aynı düğünde denk gelmek"],
    ["İlk gece ‘kaç yaşındasın’", "İlk gece hiç sormamak"],
    ["Seni tanıtan bir lakap", "Seni anlatan bir bakış"],
    ["Kalabalıkta göz göze gelmek", "Kapıda tesadüfen çarpışmak"],
    ["Aynı şarkıda sözleri bilmek", "Aynı yemeği aynı anda ısmarlamak"],
  ],
  yemek: [
    ["Sabah ilk yudum kahve", "Sabah ilk yudum çay"],
    ["Tatlıya doyamamak", "Tuzluyu abartmak"],
    ["Bir tepsi pizza paylaşmak", "Tek başına dev bir burger"],
    ["Bol tereyağlı makarna", "Tane tane pilav"],
    ["Soğuk günde çorba", "Yaz akşamı salata"],
    ["Yemeği yakacak kadar acı", "Lezzeti bozmayan sade"],
    ["Balık ekmek keyfi", "İyi bir ızgara et"],
    ["Gece sokak lezzeti", "Rezervasyonlu şef tabağı"],
    ["Kahvaltıyı asla kaçırmamak", "Gece 01.00 tostunu kaçırmamak"],
    ["Külah dondurma", "Fırından yeni sütlaç"],
    ["İnce lahmacun, bol limon", "Kıymalı pide, yanında ayran"],
    ["Annenin mantısı", "Komşunun böreği"],
    ["Köpüklü ayran", "Buz gibi şalgam"],
    ["Antep baklavası", "Sıcak künefe"],
    ["Domatesi bol menemen", "Peynirli omlet"],
    ["Mangal dumanı", "Fırın kokusu"],
    ["Masadaki her tabağı paylaşmak", "Kendi tabağına gömülmek"],
    ["Hesabı net ayırmak", "Sıra ile ısmarlamak"],
    ["Yemeği önce fotoğraflamak", "Gelir gelmez dalmak"],
    ["Baharatı abartmak", "Tuzu bile az kaçırmak"],
    ["Buharı üstünde mercimek", "Soğuk bir meze tabağı"],
    ["Annemin ev yemeği", "Hiç gitmediğin bir mekân"],
    ["Tatlıyı başta yemek", "Tatlıyı sonda hak etmek"],
    ["Tabağı sosla yıkamak", "Sosu kenarda bırakmak"],
    ["Ekmekle tabağı silmek", "Ekmeğe hiç dokunmamak"],
    ["Herkes aynı siparişi versin", "Herkes farklı sipariş etsin, tadımlansın"],
    ["Açık, kıtlama çay", "Koyu, demli çay"],
    ["Mevsim meyvesi tabağı", "Bir kutu çikolata"],
    ["Eminönü’nde balık ekmek", "Gece kokoreç"],
    ["Pazar kahvaltısı", "Maç sonrası tost"],
    ["İstanbul’da midye dolma", "Adana’da ciğer"],
    ["Çiğ köfteyi acılı yemek", "İçli köfteyi patlatmak"],
    ["Kumpir mi, yoksa durum mu", "Tost mu, yoksa döner mi"],
    ["Sahurda çorba", "İftarda ilk lokma hurma"],
    ["Simit + çay iskelesinde", "Poğaça + kahve yolda"],
    ["Evde menemen partisi", "Dışarıda serpme kahvaltı"],
    ["Tantuni acılı", "Islak hamburger"],
    ["Kaymaklı bal", "Tahin pekmez"],
    ["Kışın salep", "Yazın limonata"],
    ["Annenin dolması", "Babaanne böreği"],
    ["Tabağa yoğurt", "Tabağa pul biber"],
    ["Pideci köşesi", "Çorbacı dumanı"],
    ["İlk lokmayı karşıya uzatmak", "Son lokmayı kendine saklamak"],
    ["Yemeği ayakta kapmak", "Masada ağır ağır yemek"],
    ["Pazar pazarı + gözleme", "Cuma akşamı balık"],
    ["Çayı bardakta içmek", "Çayı ince belliyle yudumlamak"],
    ["Sosu ekmeğe bandırmak", "Sosu kaşıkla içmek"],
    ["Bir tabak daha", "Bir çay daha"],
  ],
  karakter: [
    ["Her şeyi planlamak", "Kapıdan çıkınca karar vermek"],
    ["Ezana kalkmak", "Gece 3’te hâlâ ayakta olmak"],
    ["Direksiyon sende olsun", "Akışa bırakıp yolcu olmak"],
    ["Az konuşup öz konuşmak", "Masayı hikâyeyle doldurmak"],
    ["Tek başına kazanmak", "Beraber kazandığını paylaşmak"],
    ["Gözünü karartıp risk almak", "Güvende kalıp emin yürümek"],
    ["Hemen özür dilemek", "Sözle değil işle telafi etmek"],
    ["Öne çıkıp lider olmak", "Arkadan sessizce yönlendirmek"],
    ["Duyguyu yüzüne yansıtmak", "İçinde evrilmesini beklemek"],
    ["Her detayı kusursuz yapmak", "İdare eder deyip ilerlemek"],
    ["Kalabalıktan şarj olmak", "Yalnızlıktan şarj olmak"],
    ["Eskiye bağlı kalmak", "Yeniyi merak etmek"],
    ["İnat edip sonuna kadar gitmek", "Uyum sağlayıp yolu kısaltmak"],
    ["Her şeye bir kere şüphe", "İnsanlara bir kere güven"],
    ["Çantan eczane gibi düzenli", "Çantanda kayıp bir medeniyet"],
    ["Dakikasına sadık", "‘5 dakika’ deyip 20 gelen"],
    ["Sert bir eleştiri duymak", "İçten bir övgü duymak"],
    ["Kural koyan olmak", "İstisna yapan olmak"],
    ["Hemen karar vermek", "İki kere düşünmek"],
    ["Sözünde durmak", "Duruma göre esnemek"],
    ["Gülerek geçiştirmek", "Ciddileşip çözmek"],
    ["Önde yürümek", "Yanda omuz omuza yürümek"],
    ["Detay avcısı olmak", "Büyük resmi gören olmak"],
    ["Sessiz güç", "Görünür neşe"],
    ["Unutup bağışlamak", "Unutmamak ama barışmak"],
    ["Kendi yolunu çizmek", "Beraber yol yürümek"],
    ["Az eşya, ferah ev", "Anı dolu, kalabalık ev"],
    ["Sormadan yardıma koşmak", "Önce ‘ister misin’ diye sormak"],
    ["Yüz yüze anlatmak", "Yazarak anlatmak"],
    ["İç sesini dinlemek", "En yakınını dinlemek"],
    ["İlk sen özür dilersin", "Karşı tarafın gelmesini beklersin"],
    ["Kavga edince kapıyı çarpmak", "Kavga edince masada kalmak"],
    ["Herkese aynı yüz", "Sevdiklerine başka yüz"],
    ["Sırları gömmek", "Derdini dökmek"],
    ["Kontrol sende dursun", "Birine teslim etmek"],
    ["‘Olur’ deyip sonra pişman", "‘Olmaz’ deyip sonra merak"],
    ["Gülünce gözün kaybolsun", "Kızınca bakışın keskin olsun"],
    ["Sözünü esirgememek", "Usulünce söylemek"],
    ["İlk izlenimde karar", "İnsanı üçüncü günde tanımak"],
    ["Kendini övmeden duramamak", "Başkasının seni anlatmasını beklemek"],
    ["Plan B’n hep hazır", "Plan A yetmezse doğaçlama"],
    ["Sessizce gurur duymak", "Sevincini cama yazmak"],
    ["Affetmesi kolay", "Güvenmesi zor"],
    ["Kalabalıkta kaybolmak", "Kalabalıkta fark edilmek"],
    ["‘Ben hallederim’ demek", "‘Birlikte bakarız’ demek"],
    ["İçinden geldiği gibi yaşamak", "Ne uygunsa onu yapmak"],
    ["Küçük şeylere kızmak", "Büyük şeylere bile gülmek"],
    ["Sözünün eri görünmek", "Sürprizleriyle sevilmek"],
  ],
  gunluk: [
    ["Sabah koşusu", "Akşam mahalle turu"],
    ["Duşta türkü", "Mutfakta türkü"],
    ["Alarmı beş kere ertelemek", "İlk alarmda yataktan fırlamak"],
    ["Metrobüste sıkışmak", "Yürüyerek terlemek"],
    ["Bildirimleri açık bırakmak", "Rahatsız etmeyi açmak"],
    ["Cebinde kâğıt not", "Telefona yarım cümle"],
    ["Evi toplamadan çıkmamak", "Dağınık bırakıp kapıyı çekmek"],
    ["Öğleden sonra şekerleme", "Gece bir saat daha"],
    ["Yağmurda evde çay", "Yağmurda dışarıda yürümek"],
    ["Her gün aynı kahve", "Her gün tezgâhta yeni bir şey"],
    ["Çamaşırı makineden sıcak almak", "Makinede unutup buruşturmak"],
    ["Pazartesi’ye küfretmek", "Pazartesi’yi sıfır günü saymak"],
    ["Kulaklıkla kendi dünyan", "Etrafın sesini dinlemek"],
    ["Mesajı anında yanıtlamak", "Kuyrukta bekletmek"],
    ["Alışveriş listesiyle markete", "Rafta kaybolup fazla almak"],
    ["Erken yatıp zinde kalkmak", "‘Bir bölüm daha’ deyip batmak"],
    ["Buharlı sıcak duş", "Uykuyu açan soğuk duş"],
    ["Pencereyi sonuna kadar açmak", "Klimayı sonuna kadar açmak"],
    ["Ayakkabıyı kapıda bırakmak", "Terliği unutup içeri girmek"],
    ["Güne sessizlikle başlamak", "Güne yüksek sesle başlamak"],
    ["Akşam yemeğini evde kurmak", "Kapıya sipariş yağdırmak"],
    ["Hafta içi asker disiplini", "Hafta sonu tam kaos"],
    ["Saati bozmadan yaşamak", "Rötarı hayata katmak"],
    ["Tek tabak görünce yıkamak", "Eviyeyi biriktirmek"],
    ["Güneşe karşı oturmak", "Gölgede kuytu köşe"],
    ["İşe hep aynı yoldan", "Her gün başka sokak"],
    ["Çantada powerbank", "Şarjın yüzde 3’üne güvenmek"],
    ["Kıyafeti akşamdan asmak", "Sabah dolapta kriz"],
    ["Sessiz ev", "Arkada dizi açık ev"],
    ["Erken saatte market", "Kapanışa son dakika market"],
    ["Sabah simit kuyruğu", "Akşam ekmek kuyruğu"],
    ["Otobüste ayakta gitmek", "Bir sonraki otobüsü beklemek"],
    ["Çayı demleyip beklemek", "Poşet çayı aceleyle banmak"],
    ["Evi süpürüp rahatlamak", "Tozu yarına bırakmak"],
    ["Telefonu şarja unutmak", "Kulaklığı evde unutmak"],
    ["Pazar uykusu", "Pazar kahvaltısı"],
    ["Yolda podcast", "Yolda sessizlik"],
    ["Aynı pijamayla tüm kış", "Her gece başka bir tişört"],
    ["Kapıyı çift kilitlemek", "‘Çıkarken kilitledim ya’ deyip dönmek"],
    ["Bulaşığı gece yıkamak", "Sabah kirli tencerelere uyanmak"],
    ["Hava durumuna bakıp çıkmak", "Çıkıp havaya kızmak"],
    ["Asansör beklemek", "Merdiveni çıkmak"],
    ["Çamaşırı ütülemek", "Buruşuk giyip umursamamak"],
    ["Akşam duşu", "Sabah duşu"],
    ["Yatağı düzeltmeden çıkmamak", "Yorganı öylece bırakmak"],
    ["Sütü sonuna kadar içmek", "Buzdolabında unutup ekşitmek"],
    ["Komşuya günaydın demek", "Asansörde yere bakmak"],
    ["Geceden alarm kurmak", "Şansa sabaha kalmak"],
  ],
  hayal: [
    ["Pencereden deniz görünen ev", "Kapıdan orman başlayan ev"],
    ["Zamanı bir an durdurmak", "Gelecekten bir sayfa görmek"],
    ["Çatılarda uçabilmek", "Kalabalıkta görünmez olmak"],
    ["Bir yıl dünyayı gezmek", "Bir yıl bir zanaat öğrenmek"],
    ["Herkesin tanıdığı biri olmak", "Kimsenin karışmadığı biri olmak"],
    ["Geçmişteki haline bir mektup", "Gelecekteki haline bir mektup"],
    ["Hiçbir şeyi unutmamak", "Hiçbir şeyde paniklememek"],
    ["Issız bir ada hayatı", "Büyük şehrin ışığı"],
    ["Bir kitap yazmış olmak", "Bir film çekmiş olmak"],
    ["Sonsuz uçak bileti", "Dünyanın her yerinde bir yatak"],
    ["Tek büyük dilek", "Üç küçük dilek"],
    ["Hayvanların dilinden anlamak", "Her insanın dilinden anlamak"],
    ["Gece hiç bitmesin", "Yaz hiç bitmesin"],
    ["Sahilde küçük bir kahve", "Şehirde küçük bir sahne"],
    ["Zamanda geriye gitmek", "Yıldızlara doğru gitmek"],
    ["Kimsenin bilmediği bir iyilik", "Herkesin gördüğü bir alkış"],
    ["Kendi adanı kurmak", "Kayıp bir şehri bulmak"],
    ["Bir müzenin anahtarı sende", "Bir orkestranın bastonu sende"],
    ["Ömür boyu yaz", "Ömür boyu sonbahar"],
    ["Tekrar 18 olmak", "Bilge 80 olmak"],
    ["Açılınca başka şehre çıkan kapı", "Her kilidi açan bir anahtar"],
    ["Kütüphanede kaybolmak", "Mutfakta kaybolmak"],
    ["Dünyayı değiştiren bir fikir", "Birini değiştiren bir söz"],
    ["Adın bir sokağa verilsin", "İz bırakıp isimsiz kal"],
    ["Kendi takımını kurmak", "Kendi lokantanı açmak"],
    ["Yıldızların altında uyumak", "Gökdelenin tepesinde uyanmak"],
    ["Hiç korkmamak", "Hiç pişman olmamak"],
    ["Bir gün padişah", "Bir ömür gezgin"],
    ["Elinde bir saz", "Elinde bir fırça"],
    ["Kaybolmuş bir harita", "Bitmemiş bir mektup"],
    ["Dilek tutulan bir kuyu", "Dilek yazılan bir taş"],
    ["Bir gün herkesin rüyasına girmek", "Kimsenin rüyasını görmemek"],
    ["Yağmuru durdurabilmek", "Güneşi çağırabilmek"],
    ["Kendi adınla bir türkü", "Kendi adınla bir yemek"],
    ["Bir gece İstanbul’u boş bulmak", "Bir gece İstanbul’u ilk kez görmek"],
    ["Uçaktan atlayıp süzülmek", "Denizin dibine kadar inmek"],
    ["Geçmişteki bir hatayı silmek", "Gelecekteki bir pişmanı önlemek"],
    ["Konuşmadan anlaşmak", "Her şeyi kelimesiz hissetmek"],
    ["Bir evin kapısı hep sana açık", "Bir şehrin her sokağı sana aşina"],
    ["Ömür boyu yaz tatili", "Ömür boyu bayram sabahı"],
    ["Kendi sesinle bir plak", "Kendi yüzünle bir tablo"],
    ["Kaybolup yeni bir hayat", "Bulunup eski hayatına dönmek"],
    ["Bir dileğin duyulsun", "Bir sırrın hiç duyulmasın"],
    ["Masallardaki gibi bir orman", "Şarkılardaki gibi bir şehir"],
    ["Zamanın yavaş aktığı bir köy", "Zamanın uçtuğu bir gece"],
    ["Tekrar ilk aşkını yaşamak", "Hiç yaşanmamış bir aşkı yaşamak"],
    ["Dünyanın sonuna bir bilet", "Evin yolunu bilen bir kalp"],
    ["Görünmeden yardım etmek", "Görünüp umut olmak"],
  ],
  komik: [
    ["Yanlış isimle hitap etmek", "Yanlış masaya oturmak"],
    ["Çorabın tekini kaybetmek", "Şarj aletini evde unutmak"],
    ["Gülünce sesin tuhaf çıkmak", "Yerken laf yetiştirmek"],
    ["Düğünde fazla açılmak", "Türküde sözü uydurmak"],
    ["Selfie’de gözün kapanması", "Grup fotoğrafında kaybolmak"],
    ["Yanlış sohbete gülmek", "Yanlış kişiye el sallamak"],
    ["Çaya tuz atmak", "Ayrana şeker karıştırmak"],
    ["Asansörde mırıldanmak", "Merdivende nefessiz kalmak"],
    ["İnatla kaybolmak", "İnatla yol sormamak"],
    ["Kahveyi masaya devirmek", "Hesabı ıslatmak"],
    ["Birinin taklidini yapmak", "Eski bir figürü hatırlamak"],
    ["Yanlış odaya dalmak", "Yanlış durağa inmek"],
    ["Gülmekten su burnundan gelmek", "Hıçkırığı bir türlü kesememek"],
    ["Kedi gibi kanepeye sızmak", "Köpek gibi kapıya koşmak"],
    ["İki çorap ayrı renk", "Tişört ters giyilmiş"],
    ["Espri patlamayınca o sessizlik", "Espriyi kendin anlatıp kendin gülmek"],
    ["Menüde on dakika kaybolmak", "Garsona üç kere aynı şeyi sormak"],
    ["Fotoğrafta hep gözün kapalı", "Fotoğrafta hep ağzın açık"],
    ["Yanlış çalma listesi", "Yanlış saate kurulu alarm"],
    ["Ağzın doluyken konuşmak", "Gülerken içecek burnundan gelmek"],
    ["İnatçı fermuar", "Kaybolan ev anahtarı"],
    ["Kendi ses kaydından ürkmek", "Kendi dans videondan ürkmek"],
    ["Öğleden sonra günaydın demek", "Sabah 10’da iyi geceler demek"],
    ["Masada herkesin yemeğini tatmak", "Kendi tabağını kimseye kaptırmamak"],
    ["Gülünce dizinle masayı vurmak", "Gülünce suyu burnundan çıkarmak"],
    ["İsmini hecelete hecelete anlatmak", "Adres tarifinde kendini kaybetmek"],
    ["Çantanın dibini boşaltmak", "Cebinden sürpriz kâğıt çıkarmak"],
    ["Yanlış filmi izledim demek", "Yanlış şarkının sözünü söylemek"],
    ["Kaşığı yere düşürmek", "Peçeteyi rüzgâra kaptırmak"],
    ["Komik bir yalan uydurmak", "Daha komik bir gerçeği itiraf etmek"],
    ["WhatsApp’ta yanlış kişiye sesli mesaj", "Aile grubuna yanlış emoji"],
    ["Toplu taşımada yüksek sesle konuşmak", "Toplu taşımada yanlış durakta inmek"],
    ["İmamın bildiği yere ‘amin’ demek", "Herkesin güldüğü yere geç kalmak"],
    ["Çayı içerken ürkütülmek", "Simidi ısırırken fotoğrafın çekilmesi"],
    ["Yanlış eve anahtar denemek", "Yanlış arabaya binmeye çalışmak"],
    ["Zoom’da mikrofon açık unutulmak", "Toplantıda kameraya takılı kalmak"],
    ["‘Buyur’ deyip kapıyı başkasına açmak", "‘Alo’ deyip yanlış numaraya çıkmak"],
    ["Cüzdanı evde unutmak", "Telefonu restoranda unutmak"],
    ["Tuzluğu şeker sanmak", "Biberliği pul biber sanmak"],
    ["Gülerken yere düşmek", "Otururken sandalyeyi kaybetmek"],
    ["Aynı hikâyeyi masaya üçüncü kez anlatmak", "Hikâyenin sonunu unutmak"],
    ["Yanlış ‘ellerine sağlık’", "Yanlış ‘geçmiş olsun’"],
    ["Asansörde yanlış kata basmak", "Kapıyı çekmeden ‘çek’ demek"],
    ["Çorba içerken öksürmek", "Ayran içerken gülmek"],
    ["Cebinde delik olduğunu geç anlamak", "Ayakkabı bağının çözüldüğünü geç anlamak"],
    ["‘Nereden tanışıyoruz’ diye sormak", "Tanıdığın birine ‘tanıştığımıza memnun oldum’ demek"],
    ["Otoparkta arabayı kaybetmek", "AVM’de katı karıştırmak"],
    ["Masada herkesin adını karıştırmak", "Kendi siparişini unutup başkasınınkini yemek"],
  ],
  tatil: [
    ["Deniz kenarında bir hafta", "Dağ evinde bir hafta"],
    ["Otelin konforu", "Çadırın macerası"],
    ["Gün gün yazılı plan", "Sabah kalkıp nereye eserse"],
    ["Sabahın köründe uçak", "Gece otobüsünün rüyası"],
    ["Sevdiğin yere tekrar dönmek", "Hiç gitmediğin bir yere uçak"],
    ["Bütün gün müze", "Bütün gün plaj"],
    ["Şehirde kaybolmak", "Köyde zamanı unutmak"],
    ["Valizi sonuna kadar doldurmak", "Sadece bir sırt çantası"],
    ["Yerelin yediği yerde yemek", "Güvenli, bildiğin lezzet"],
    ["Gün doğumunu izlemek", "Gün batımını kaçırmamak"],
    ["Tek başına yol", "Kalabalık kervan"],
    ["Ege adası", "Kapadokya perisi"],
    ["Tren penceresinde saatler", "Arabayla playlist’le kilometreler"],
    ["Rezervasyonlu restoran", "Sokağın en kalabalık tezgâhı"],
    ["Her köşeyi fotoğraflamak", "Sadece bakıp aklında tutmak"],
    ["İlk gün otele gömülmek", "İlk gün şehri arşınlamak"],
    ["Uludağ’da kar", "Kaş’ta deniz"],
    ["Her şey dâhil tatil", "Sokak sokak yemek"],
    ["Haritayı kaybetmek", "Telefonu kaybetmek"],
    ["Tarihî bir pansiyon", "Yeni açılmış tasarım otel"],
    ["Göl kenarında çay", "Şelalenin altında serinlik"],
    ["Gece pazarı", "Sabah balık hali"],
    ["Bir ülkede on gün", "On ülkede on gün"],
    ["Yürüyerek kaybolmak", "Taksiyle yetişmek"],
    ["Hatıra dolu bavul", "Sadece kafanda anılar"],
    ["Kamp ateşi", "Otel jakuzisi"],
    ["Yolda müziği son ses", "Yolda camı açıp sessizlik"],
    ["Aynı otele her yıl", "Her yıl başka bir kıta"],
    ["Erken check-in", "Geç check-out"],
    ["Tatilde iş mailine bakmamak", "Bir göz atıp kapatmak"],
    ["Ayvalık’ta gün batımı", "Boğaz’da vapur"],
    ["Gap turu", "Ege turu"],
    ["Yurt dışında kaybolmak", "Memlekette bir köyde kaybolmak"],
    ["Valiz tartıda fazla gelmek", "Uçağı kıl payı kaçırmak"],
    ["Otel kahvaltısını abartmak", "Sokağa çıkıp simit kapmak"],
    ["Aynı kişiyle her tatil", "Her tatilde yeni bir masa"],
    ["Yolculukta pencere kenarı", "Yolculukta koridor, ayak uzar"],
    ["Tatilde hiç plan yok", "Tatilde her saat dolu"],
    ["Karadeniz yaylası", "Akdeniz koyu"],
    ["İlk gün yağmur", "Son gün yağmur"],
    ["Pansiyonun ev yemeği", "Şehrin en ünlü restoranı"],
    ["Bavulu evde unuttuğunu havalimanında anlamak", "Pasaportu evde unuttuğunu havalimanında anlamak"],
    ["Gün batımında çay", "Gece yarısı deniz"],
    ["Bir hafta telefon kapalı", "Bir hafta her anı paylaşmak"],
    ["Yerel otobüsle şehir", "Kiralanmış arabayla özgürlük"],
    ["Aynı denize her yaz", "Her yaz başka bir deniz"],
    ["Dönüş biletini uzatmak", "Dönüşte evin kokusunu özlemek"],
    ["Tatilde aşk", "Tatilde dostluk"],
  ],
  kultur: [
    ["Karanlık bir sinema", "Canlı bir tiyatro"],
    ["Diziyi bir gecede bitirmek", "Haftada bir bölüm beklemek"],
    ["Kalın bir roman", "Tek bir şiir"],
    ["Açık hava konseri", "Sessiz bir sergi"],
    ["Yerli bir film", "Altyazılı bir yabancı"],
    ["Kırıp geçiren komedi", "Nefes tutturan gerilim"],
    ["Altyazıyla orijinal", "İyi bir dublaj"],
    ["Canlı müzik, kalabalık", "Kulaklık ve yalnızlık"],
    ["Eski klasikler", "Bu yazın hitleri"],
    ["Yolda podcast", "Arabada radyo"],
    ["Müzede kaybolmak", "Sahilde kitap"],
    ["Stand-up gecesi", "Müzikal akşamı"],
    ["Belgesel", "Bilim kurgu"],
    ["Yüzüncü kez izlenen film", "Hiç bitmeyen dizi"],
    ["Kütüphanenin sessizliği", "Plakçının tozu"],
    ["Gece yarısı seansı", "Öğleden sonra matinesi"],
    ["Şarkı sözünü ezbere bilmek", "Melodiyi ıslıkla tutturmak"],
    ["Yazar olmak", "Yönetmen olmak"],
    ["Perde arkasında kalmak", "Sahne ışığında durmak"],
    ["Çizgi roman yığını", "Uzun bir roman"],
    ["Kalkıp dans etmek", "Oturup sadece dinlemek"],
    ["Karanlık salon", "Açık hava sineması"],
    ["Bir şarkıda gözün dolmak", "Bir sahnede kahkaha atmak"],
    ["Konsolda gece", "Masa oyununda gece"],
    ["Bilet kuyruğunda beklemek", "Evde yayına gömülmek"],
    ["Koroda bir ses olmak", "Tek başına sahneye çıkmak"],
    ["Siyah beyaz bir film", "Renk cümbüşü bir film"],
    ["Şiir gecesi", "Açık mikrofon"],
    ["E-kitabın rahatlığı", "Kâğıdın kokusu"],
    ["Jeneriği sonuna kadar izlemek", "Hemen kapatıp yatağa gitmek"],
    ["Türkçe rock", "Arabesk gece"],
    ["Yeşilçam tekrarı", "Yeni yerli dizi"],
    ["Konserde ön sıra", "Konserde arkada, rahat"],
    ["Kitabı bitirmeden spoiler yemek", "Spoiler’dan kaçıp merakla okumak"],
    ["Aynı şarkıyı on kez dinlemek", "Her gün yeni bir liste"],
    ["Tiyatroda birinci perde ağlamak", "Sinemada jenerikte alkışlamak"],
    ["Plak çevirmek", "Spotify’da kaybolmak"],
    ["Bir şiiri ezberlemek", "Bir filmin repliğini ezberlemek"],
    ["Festivalde çamur", "Salon konserinde koltuk"],
    ["Dizi karakterine sinirlenmek", "Film kahramanına âşık olmak"],
    ["Kitabı not alarak okumak", "Kitabı bir solukta yutmak"],
    ["Sahneye çıkma hayali", "Sahne ışığını izleme keyfi"],
    ["Eski bir kaset", "Yeni bir kulaklık"],
    ["Aynı filmi sevgilinle izlemek", "Aynı filmi tek başına izlemek"],
    ["Gülmekten sahneyi kaçırmak", "Ağlamaktan altyazıyı kaçırmak"],
    ["Bir kitabın sonunu tahmin etmek", "Bir filmin sonuna şaşırmak"],
    ["Klasik müzik", "Sokak müziği"],
    ["İlk konserin heyecanı", "Yüzüncü konserin rahatlığı"],
  ],
  dostluk: [
    ["Eski, köklü dost", "Yeni ama kör kütük samimi"],
    ["Her gün ‘n’aber’", "Ayda bir uzun sohbet"],
    ["Sırrını mezara götürmek", "Dürüstçe yüzüne söylemek"],
    ["Birlikte rahatça susmak", "Birlikte kahkahaya boğulmak"],
    ["Zor günde kapına dayanmak", "İyi günde masayı kurmak"],
    ["Aynı şakayı on yıldır yapmak", "Her yıl yeni bir içe bakış"],
    ["Gece 03.00 araması", "Sabah kahvesi rutini"],
    ["Ortak bir sır", "Ortak bir hedef"],
    ["Tartışıp barışmak", "Hiç küsmeden konuşmak"],
    ["Aynı masada dört saat", "Kısa ama sık görüşmek"],
    ["Hediye almak", "Vakit ayırmak"],
    ["Seni tanıyan bir bakış", "Seni anlatan bir cümle"],
    ["Grup sohbetinde kaybolmak", "İkili sohbette açılmak"],
    ["Yol arkadaşı", "Sır arkadaşı"],
    ["Aynı şehri paylaşmak", "Uzak ama bağlı kalmak"],
    ["Özür beklememek", "Özürü büyütmek"],
    ["Birlikte yemek yapmak", "Birlikte yemek ısmarlamak"],
    ["Doğum gününü şaşmamak", "Rastgele bir günde sürpriz"],
    ["Sert dürüstlük", "Yumuşak teselli"],
    ["Aynı takım forması", "Aynı çalma listesi"],
    ["Sessizce yardım", "Açıkça omuz vermek"],
    ["Eski fotoğraflara gülmek", "Yeni planlar yazmak"],
    ["Kavga etmeden ayrılmak", "Kavga edip daha bağlanmak"],
    ["Bir sırrı emanet etmek", "Bir hayali emanet etmek"],
    ["Seni utandıran anı", "Seni gururlandıran anı"],
    ["Aynı masada susmak rahat", "Aynı masada hiç susmamak"],
    ["Dostun yemeğini yemek", "Dostuna son lokmayı vermek"],
    ["Yol tarif etmek", "Beraber kaybolmak"],
    ["Aynı şakaya kızmak", "Aynı şakaya bayılmak"],
    ["El sıkışmak", "Omuz omuza yürümek"],
    ["Dostunla derbi izlemek", "Dostunla uzun yol"],
    ["Hasta gününde çorba getirmek", "İyi gününde hesabı kapatmak"],
    ["Seni kötü gününde tanıyan", "Seni iyi gününde tanıyan"],
    ["Aynı masada küslüğü bitirmek", "Telefonda barışmak"],
    ["Dostunun ailesine ‘bizden’ demek", "Dostunun sırrına ‘bende’ demek"],
    ["Birlikte taşınmak", "Birlikte iş kurmak"],
    ["Seninle aynı takımı tutması", "Seninle aynı yemeği sevmesi"],
    ["Kırgınlığı hemen konuşmak", "Kırgınlığı zamana bırakmak"],
    ["Düğününde yanında olmak", "Hastane kapısında yanında olmak"],
    ["Aynı lakabı on yıl taşımak", "Her dönemde yeni bir hatıra"],
    ["Dostunla sessiz çay", "Dostunla gürültülü gece"],
    ["Seni utandırınca gülmek", "Seni utandırınca örtmek"],
    ["Aynı evi paylaşmış olmak", "Aynı sırrı paylaşmış olmak"],
    ["Dostunun eski sevgilisini tanımak", "Dostunun yeni işini ilk duymak"],
    ["Bir mesajla yetinmek", "Kapıya dayanmak"],
    ["Aynı şarkıda göz göze gelmek", "Aynı yemekte tabağı paylaşmak"],
    ["Dostlukta kıskançlık", "Dostlukta kayıtsızlık"],
    ["Son sözü sen söylemek", "Son sözü ona bırakmak"],
  ],
  para: [
    ["Biriktirip beklemek", "Güzel bir şey için harcamak"],
    ["Cebinde nakit", "Cüzdanda kart"],
    ["Pahalı ve az", "Uygun ve bol"],
    ["Hesabı tek seferde kapamak", "Hesabı kalem kalem bölmek"],
    ["İkinci el hazine", "Yeni ve garantili"],
    ["Maaş gününü kutlamak", "Maaş gününü planlamak"],
    ["Sürpriz hediye", "Listenin başındaki hediye"],
    ["Ucuza kaçmak", "Bir kez olsun şımarmak"],
    ["Yatırım konuşmak", "Tatil konuşmak"],
    ["Bahşişi yuvarlamak", "Hesabı kuruşuna bölmek"],
    ["İndirim kovalamak", "Vaktini kovalamak"],
    ["Bir ev almak", "Dünyayı gezmek"],
    ["Sigorta poliçesi", "Macera kumbarası"],
    ["Logosu görünen marka", "Kalitesi sessiz dursun"],
    ["Ortak kumbara", "Ayrı cüzdan"],
    ["Piyango bileti", "Düzenli birikim"],
    ["Tek lüks akşam", "On mütevazı akşam"],
    ["Borcu hemen kapatmak", "Taksiti sevmek"],
    ["Pahalı bir kahve", "Pahalı bir kitap"],
    ["İlk maaşın anısı", "İlk birikimin anısı"],
    ["Pazarlık etmek", "Fiyatı kabul edip geçmek"],
    ["İkram etmek", "İkramı kabul etmek"],
    ["Az kazanıp rahat", "Çok kazanıp tempo"],
    ["Emeklilik hayali", "Bugünün keyfi"],
    ["Ortak hesap", "Net bölüşmek"],
    ["Kumbarayı kırmak", "Kumbarayı büyütmek"],
    ["İyi bir ayakkabı", "İyi bir yemek"],
    ["Döviz konuşmak", "Dondurma konuşmak"],
    ["Fatura alarmı", "Sürpriz ek ücret"],
    ["‘Ben öderim’", "‘Sırayla ödeyelim’"],
    ["Bayram harçlığını biriktirmek", "Bayram harçlığını hemen yemek"],
    ["İkinci el araba", "Sıfır ama küçük ev"],
    ["İndirim günü kuyruk", "Normal günde rahat alışveriş"],
    ["Arkadaşa borç vermek", "Arkadaştan borç istememek"],
    ["Maaşın yarısını eve", "Maaşın yarısını tatile"],
    ["Markette kasa önünde vazgeçmek", "Kasada ‘bir de şunu’ demek"],
    ["Altın almak", "Yol parası biriktirmek"],
    ["Hesabı görünce gülmek", "Hesabı görünce susmak"],
    ["İyi bir mont", "İyi bir telefon"],
    ["Çocuğuna birikim", "Kendine bir akşam"],
    ["Pazarlıkta son kuruş", "‘Fazla konuşmayalım’ deyip almak"],
    ["İkramiyeyi gizlemek", "İkramiyeyi masada anlatmak"],
    ["Kira + ev rahatı", "Kira yok, ev sahibi stresi"],
    ["‘Bu ay sıkıyız’", "‘Bu ay bir yere gidelim’"],
    ["Nakit verenin yüzü", "Kart çekenin rahatlığı"],
    ["Birikmiş tatil parası", "Birikmiş ‘güvenli gün’ parası"],
    ["İsrafı görünce sinirlenmek", "İsrafı görünce gülmek"],
    ["Hesabı unutup çıkmak", "Hesabı iki kere kontrol etmek"],
  ],
  cocukluk: [
    ["Mahallede akşama kadar dışarı", "İçeride Lego imparatorluğu"],
    ["Çizgi film kuşağı", "Apartman önünde saklambaç"],
    ["Yaz tatili köy", "Yaz tatili deniz"],
    ["Okul servisinin uykusu", "Yürüyerek okula gitmek"],
    ["Öğretmenin gözdesi", "Teneffüsün kralı"],
    ["Gizli günlük", "Duvara çizilen resim"],
    ["İlk bisiklet", "İlk paten"],
    ["Abur cubur yasak ev", "Abur cubur serbest ev"],
    ["Kardeşle aynı oda", "Tek başına oda"],
    ["Yaz okulu", "Boş, sonsuz yaz"],
    ["Gece masalı", "Gündüz çizgi roman"],
    ["Annemin yemeği", "Babamın pazar kahvaltısı"],
    ["İlk evcil hayvan", "İlk en yakın arkadaş"],
    ["Kar tatili sevinci", "Yaz tatili bitmesin isyanı"],
    ["Ödevi akşam bitirmek", "Ödevi sabah otobüste yazmak"],
    ["Saklı bir defter", "Açık bir günlük"],
    ["Mahalle maçı", "Bilgisayar başı"],
    ["Kırmızı karne korkusu", "Takdir belgesi gururu"],
    ["Büyümek istemek", "Çocuk kalmak"],
    ["Parkta salıncak", "Denizde simit"],
    ["İlk sahne korkusu", "İlk gol sevinci"],
    ["Yastık savaşı", "Su savaşı"],
    ["Gizli kulübe", "Çatı katı"],
    ["Öğle uykusu isyanı", "Gece erken yatmak isyanı"],
    ["Bayram harçlığı", "Bayram öpücüğü"],
    ["İlk konser hayali", "İlk maç hayali"],
    ["Sınıfta arka sıra", "Sınıfta ön sıra"],
    ["Büyüyünce öğretmen", "Büyüyünce astronot"],
    ["Kardan adam", "Kumdan kale"],
    ["Masal sonu mutlu bitsin", "Biraz korksun ki eğlensin"],
    ["Şeker bayramı", "Kurban bayramı köyü"],
    ["Okul çıkışı simit", "Okul çıkışı oyuncakçı vitrini"],
    ["Annemin ‘dersine bak’ı", "Babamın ‘dışarı çık’ı"],
    ["İlk dişin düşmesi", "İlk bisikletten düşmen"],
    ["Yazın sineklik arkasından bakmak", "Kışın camda nefesle resim"],
    ["Teneffüste kuyruk", "Ders bitiminde kapıya hücum"],
    ["Öğretmenin tahtaya yazdığı isim", "Defterine çizdiğin kalp"],
    ["Mahalle ablası / abisi olmak", "Mahallenin en küçüğü olmak"],
    ["Cuma günü karne", "Pazartesi günü ilk ders"],
    ["Sakız yasağı", "Koşunca düşme yasağı"],
    ["İlk cep harçlığı", "İlk ev işi görevi"],
    ["Yatılı okul hayali", "Evden hiç ayrılmama hayali"],
    ["Çizgi film jeneriği ezber", "Okul marşı ezber"],
    ["Annemin örgü atkısı", "Babamın büyük montu"],
    ["Parkta dondurma", "Evde aşure"],
    ["İlk yalan", "İlk özür"],
    ["Kardeşinle kavga", "Kardeşinle sır"],
    ["Yazın akşam ezanı ev çağrısı", "Kışın soba başı"],
  ],
  masa: [
    ["Hesabı isteyen", "‘Bir şey daha’ diyen"],
    ["Menüyü ezberlemek", "Garsona ‘sen seç’ demek"],
    ["Pencere kenarı", "Ortadaki kalabalık masa"],
    ["Çayı taze taze içmek", "Hesap gelene kadar sohbet"],
    ["Telefonu ters çevirmek", "Bir fotoğraf izni"],
    ["Ortaya meze", "Herkes kendi tabağı"],
    ["Gürültülü, canlı masa", "Fısıltılı, sakin masa"],
    ["Erken kalkıp gitmek", "Kapanışa kadar kalmak"],
    ["Aynı mekânın müdavimi", "Her hafta yeni yer"],
    ["Çayı devirmek", "Tuzu devirmek"],
    ["Garsonla muhabbet", "Sessizce sipariş"],
    ["Tatlıyı bölüşmek", "Ayrı ayrı tatlı"],
    ["Masada oyun", "Masada dedikodu"],
    ["Bahçede oturmak", "İçeride köşe kapmak"],
    ["Hesabı şaşırınca gülmek", "Hesabı şaşırınca panik"],
    ["Su sade", "Su sodalı"],
    ["Ekmek sepeti bitsin", "Tatlı menüsü açılsın"],
    ["Kalabalık rezervasyon", "İki kişilik sürpriz"],
    ["İlk gelen siparişi verir", "Herkes gelsin diye bekler"],
    ["Klasik masa örtüsü", "Çıplak ahşap masa"],
    ["Çaydanlık masada dursun", "Tek tek ince belli"],
    ["Açık mutfağı izlemek", "Sokağı izlemek"],
    ["Hesap kâğıdını saklamak", "Hemen unutmak"],
    ["‘Bir şey daha’ turu", "‘Hesap lütfen’ turu"],
    ["Masa oyununu kaybetmek", "Hesabı kapamak"],
    ["Peçeteye şaka yazmak", "Bardak tokuşturmak"],
    ["Yemeği soğutmadan konuşmak", "Önce yemek, sonra sohbet"],
    ["Aynı masada üç saat", "İki mekân, bir gece"],
    ["Bahşişi yuvarlak bırakmak", "Bahşişi içinden geldiği gibi"],
    ["Masada sır paylaşmak", "Masada plan yapmak"],
    ["Çayı ‘demli’ diye geri göndermek", "Çayı olduğu gibi içmek"],
    ["Masada herkesin telefonu kapalı", "Masada bir hikâye, herkes dinler"],
    ["Pencere açık, sokak sesi", "İçerisi loş, müzik kısık"],
    ["İlk gelen ‘ben ısmarlarım’", "Son kalan ‘ben kapatırım’"],
    ["Aynı masada doğum günü", "Aynı masada veda"],
    ["Garsonun önerdiği", "Senin bildiğin klasik"],
    ["Masayı erken rezerve etmek", "Kapıdan ‘yer var mı’ demek"],
    ["Çayın yanında simit", "Yemeğin yanında ayran"],
    ["Hesabı görünce ‘değer’ demek", "Hesabı görünce ‘bir dahaki sefere ev’ demek"],
    ["Masada eski bir sırrı açmak", "Masada yeni bir yalanı yakmak"],
    ["Herkes aynı anda sipariş", "Sıra sıra ‘ben de ondan’"],
    ["Masada susunca rahat etmek", "Masada susunca konu aramak"],
    ["Çay tabağında lokum", "Kahve yanında su"],
    ["Aynı masada küslüğü bitirmek", "Aynı masada niyet tutmak"],
    ["Hesabı iki kere bölmek", "Hesabı kapatıp tartışmamak"],
    ["Masada birini utandırmak", "Masada birini parlatmak"],
    ["Kapanışta bir çay daha", "Kapanışta hesap ve kapı"],
    ["Masada ‘ben anlatayım’", "Masada ‘sen anlat, ben dinlerim’"],
  ],
};

export type RatherQuestion = {
  id: string;
  cat: RatherCategoryId;
  a: string;
  b: string;
};

export const RATHER_QUESTIONS: RatherQuestion[] = (
  Object.entries(RAW) as [RatherCategoryId, [string, string][]][]
).flatMap(([cat, rows]) =>
  rows.map(([a, b], index) => ({
    id: `${cat}-${index + 1}`,
    cat,
    a,
    b,
  })),
);
