export const TENTEN_PROMPTS = [
  "10’da 10 ama rakip takımın amansız taraftarı",
  "10’da 10 ama hiç espri anlamıyor",
  "10’da 10 ama annen bir türlü ısınmıyor",
  "10’da 10 ama her yere 20 dakika geç kalıyor",
  "10’da 10 ama telefonu elinden düşmüyor",
  "10’da 10 ama hiç yemek yapmıyor",
  "10’da 10 ama seninle fotoğraf çekilmek istemiyor",
  "10’da 10 ama eski sevgilisiyle hâlâ konuşuyor",
  "10’da 10 ama hesabı hiç kapatmıyor",
  "10’da 10 ama başka şehirde yaşıyor",
  "10’da 10 ama hiç dans etmiyor",
  "10’da 10 ama maç günü kayboluyor",
  "10’da 10 ama senin çalma listene gülüyor",
  "10’da 10 ama hiç sır tutamıyor",
  "10’da 10 ama ailesi her şeye karışıyor",
  "10’da 10 ama asla özür dilemiyor",
  "10’da 10 ama her şeye ‘idare eder’ diyor",
  "10’da 10 ama hiç plan yapmıyor",
  "10’da 10 ama senin arkadaşlarınla anlaşamıyor",
  "10’da 10 ama hiç kıskanmıyor",
  "10’da 10 ama hiç tatile çıkmıyor",
  "10’da 10 ama seninle aynı masada susuyor",
  "10’da 10 ama hiç hediye almıyor",
  "10’da 10 ama evde ayakkabıyla geziyor",
  "10’da 10 ama çayı şekersiz, soğuk içiyor",
  "10’da 10 ama lahmacunu asla paylaşmıyor",
  "10’da 10 ama her yemeği pul biberliyor",
  "10’da 10 ama annenin yemeğini beğenmiyor",
  "10’da 10 ama bayramda memlekete gitmiyor",
  "10’da 10 ama senin takımına küfrediyor",
  "10’da 10 ama evde hiç çay yok, sadece kahve",
  "10’da 10 ama seninle asla kavga etmiyor",
  "10’da 10 ama ailesini hiç göstermiyor",
  "10’da 10 ama senin kıyafetine karışıyor",
  "10’da 10 ama hiç kitap okumuyor",
  "10’da 10 ama dizi spoiler’ı patlatıyor",
  "10’da 10 ama araba kullanmıyor",
  "10’da 10 ama hiç dans etmiyor, düğünde oturuyor",
  "10’da 10 ama seninle fotoğrafta poz vermiyor",
  "10’da 10 ama ‘aşk’ kelimesini kullanmıyor",
  "10’da 10 ama hiç ev işi yapmıyor",
  "10’da 10 ama köpeği sevmiyor",
  "10’da 10 ama seninle aynı yastıkta uyumuyor, ayrı oda istiyor",
  "10’da 10 ama sosyal medyada ‘müsait değil’",
  "10’da 10 ama hiç ‘sen haklısın’ demiyor",
  "10’da 10 ama seninle maça gelmiyor, evde kalıyor",
  "10’da 10 ama Fener–Galatasaray–Beşiktaş derbisinde karşı tarafta",
  "10’da 10 ama hiç Türk kahvesi içmiyor",
  "10’da 10 ama soğanı sevmiyor, sofrayı bölüyor",
  "10’da 10 ama seninle asla ‘biz’ demiyor",
  "10’da 10 ama geç saatlerde kayboluyor",
  "10’da 10 ama senin ailenle yemek yemiyor",
  "10’da 10 ama hiç ‘özür dilerim’ yok, ‘geçmiş olsun’ var",
  "10’da 10 ama seninle aynı şehri beğenmiyor",
  "10’da 10 ama hiç ‘seni düşünüyorum’ yazmıyor",
  "10’da 10 ama düğünde seninle oynamıyor",
  "10’da 10 ama hiç ‘kaç para’ diye sormuyor, sen ödüyorsun",
  "10’da 10 ama seninle aynı evde dağınık yaşıyor",
  "10’da 10 ama seninle hiç tatile çıkmıyor, işi bahane",
  "10’da 10 ama senin takımının formasını giymiyor",
  "10’da 10 ama hiç ‘hadi evlenelim’ demiyor",
  "10’da 10 ama seninle aynı masada başkasını süzüyor",
  "10’da 10 ama hiç ‘yorgunum, evde kalalım’ demiyor, hep dışarı",
  "10’da 10 ama seninle aynı inancı konuşmuyor",
  "10’da 10 ama hiç ‘anneni aradım’ demiyor",
  "10’da 10 ama seninle asla ‘özür’ yok, hep ‘abartma’",
  "10’da 10 ama hiç evcil hayvan istemiyor",
  "10’da 10 ama seninle aynı şarkıda dans etmiyor",
  "10’da 10 ama hiç ‘seni kıskandım’ demiyor",
  "10’da 10 ama seninle aynı gelecekte değil, ‘bakarız’ diyor",
  "10’da 10 ama hiç ‘ben pişiririm’ yok",
  "10’da 10 ama seninle maçta karşı tribün",
  "10’da 10 ama hiç ‘geç kaldım özür’ yok",
  "10’da 10 ama seninle aynı masada telefonu çekiyor, sen yoksun",
  "10’da 10 ama hiç ‘hadi barışalım’ yazmıyor, sen yazıyorsun",
  "10’da 10 ama seninle aynı evde ‘benim alanım’ savaşı",
  "10’da 10 ama hiç ‘seni arkadaşlarıma anlatıyorum’ demiyor",
  "10’da 10 ama rakip takımın formasını evde asıyor",
  "10’da 10 ama hiç ‘bugün nasılsın’ yok, doğrudan iş",
  "10’da 10 ama seninle aynı yastıkta soğuk",
  "10’da 10 ama hiç ‘benimle kal’ demiyor",
  "10’da 10 ama seninle aynı şehirde, ayrı hayatlar",
  "10’da 10 ama hiç ‘ailece gidelim’ yok",
  "10’da 10 ama seninle aynı masada ‘ben tokum’, sen yemiyorsun",
  "10’da 10 ama hiç ‘özledim’ yok, sadece ‘görüşürüz’",
  "10’da 10 ama seninle derbide karşı tarafın tezahüratı",
  "10’da 10 ama hiç evlilik konuşmuyor, ‘zamanı değil’",
  "10’da 10 ama seninle aynı evde hiç ‘günaydın’ yok",
  "10’da 10 ama hiç ‘seni savunurum’ yok, kalabalıkta susuyor",
  "10’da 10 ama seninle aynı hayali kurmuyor",
  "10’da 10 ama rakip taraftar",
  "10’da 10 ama hiç kahkaha atmaz",
  "10’da 10 ama her cümlesi ‘aslında’",
  "10’da 10 ama masada hesabı unutuyor",
  "10’da 10 ama senin şehrini sevmiyor",
  "10’da 10 ama gece 12’de kayboluyor",
  "10’da 10 ama hiç ‘günaydın’ yazmıyor",
  "10’da 10 ama her tartışmada sessiz",
  "10’da 10 ama seninle aynı takımı tutmuyor",
  "10’da 10 ama evde terlik giymiyor",
  "10’da 10 ama çayı demli içmiyor",
  "10’da 10 ama hiç ‘özür’ demiyor",
  "10’da 10 ama her fotoğrafta poz vermiyor",
  "10’da 10 ama seninle aynı masada telefonu bırakmıyor",
  "10’da 10 ama hiç ‘hadi gidelim’ demiyor",
  "10’da 10 ama ailesi her hafta geliyor",
  "10’da 10 ama seninle aynı evde müzik yok",
  "10’da 10 ama her yemeği tuzluyor",
  "10’da 10 ama hiç ‘seni dinliyorum’ demiyor",
  "10’da 10 ama derbide karşı tribün",
] as const;

export type TenTenPrompt = {
  id: string;
  text: string;
};

export const TENTEN_QUESTIONS: TenTenPrompt[] = TENTEN_PROMPTS.map((text, index) => ({
  id: `tt-${index + 1}`,
  text,
}));
